### ISSUE TITLE
Pratica 6

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-equipo-gregorio-8us#2]
[Practica 6 Animacion de objeto 3d.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-equipo-gregorio-8us/files/14727215/Practica.6.Animacion.de.objeto.3d.pdf)

**Comment by salathiel1999** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
